# Generated by Django 2.2.3 on 2019-07-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name_plural': 'Hashtags'},
        ),
    ]
